### ISSUE TITLE
appender example not working

### ISSUE THREAD

**Issue by michael-byo** [amauryt/crystal-duckdb#3]
Hi

I'm trying to run the appender example, and getting an error using duckdb 1.3.2 on Mac OS 15.5

```In src/appender.cr:15:23

 15 | row << record.name
                    ^---
Error: undefined method 'name' for NamedTuple(name: String, age: Int32, is_active: Bool | Nil)
```

the initial example was ok. I'm wondering if using 1.3.2 (the latest duck lib) is the issue. I'm not sure how to get it to work with the 1.2.0 as I'm new to crystal (perhaps I can copy the libduckdb.dylib to the lib folder in the project). I'm wondering if you might have any advice, or can confirm it would work ok with 1.3.2 installed via homebrew.

Thanks.

**Comment by michael-byo** [comment]
ah it turns out changing record.name -> record[:name] works, so this is a good situation, and seems to work for duckdb v1.3.2 which is also great. Perhaps it's worth to update the example? I think there's also a missing comma in the records list. Thanks again for making this library.

**Comment by amauryt** [comment]
Indeed, because in the example instances of [`NamedTuple`](https://crystal-lang.org/api/1.17.1/NamedTuple.html) are used, one needs to use `named_tuple[:key]` to access the respective value. There is a typo in the examples.

However, it is not a good practice to use `NamedTuple` for this use cases, as [stated by one of the creators](https://github.com/crystal-lang/crystal/issues/6135#issuecomment-392331437) of the Crystal language.

If one needs immutable data structures one should inherit from `Struct`; there's even a convenience macro called [`record`](https://crystal-lang.org/api/1.17.1/toplevel.html#record%28__namename%2C%2Aproperties%2C%2A%2Akwargs%29-macro) for that. Otherwise, if one needs mutability, it's better to inherit from `Class`.

Therefore, I have changed the Appender example to use `Struct` via the `record` macro.
